spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:stag_db}
    username: ${DB_USER:meu_usuario}
    password: ${DB_PASSWORD:123}
  jpa:
    hibernate:
      ddl-auto: validate